# - name: Remove Docker GPG keyring file
#   become: yes
#   file:
#     path: /etc/apt/trusted.gpg.d/docker.gpg
#     state: absent

# - name: Remove Docker apt source file
#   become: yes
#   file:
#     path: /etc/apt/sources.list.d/docker.list
#     state: absent

# - name: Remove specific Docker source list files
#   become: yes
#   file:
#     path: "{{ item }}"
#     state: absent
#   with_items:
#     - /etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list
#     - /etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list.save

# - name: Uninstall conflicting packages
#   apt:
#     name: "{{ item }}"
#     state: absent
#   loop:
#     - docker.io
#     - docker-doc
#     - docker-compose
#     - docker-compose-v2
#     - podman-docker
#     - containerd
#     - containerd.io
#     - runc
#   notify: Update packages database

# - name: Install ca-certificates and curl packages
#   apt:
#     name: "{{ item }}"
#     state: latest
#   loop:
#     - ca-certificates
#     - curl

# - name: Create /etc/apt/keyrings directory
#   file:
#     path: /etc/apt/keyrings
#     state: directory
#     mode: '0755'

# - name: Download Docker GPG key
#   get_url:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     dest: /etc/apt/keyrings/docker.asc
#     mode: '0644'

# - name: Set read permissions for docker.asc file
#   file:
#     path: /etc/apt/keyrings/docker.asc
#     mode: 'a+r'

# - name: Add Docker repository entry to docker.list
#   lineinfile:
#     path: /etc/apt/sources.list.d/docker.list
#     line: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
#     create: yes
#   notify: Update packages database

# - name: Install docker packages
#   apt:
#     name: "{{ item }}"
#     state: latest
#   loop:
#     - docker
#     - docker-ce-cli
#     - containerd.io
#     - docker-buildx-plugin
#     - docker-compose-plugin



# - name: Update apt and install docker packages
#   apt:
#     name: "{{ item }}"
#     state: latest
#     update_cache: yes
#   loop:
#     - docker-ce
#     - docker-ce-cli
#     - docker.io
#     - podman-docker
#     - containerd.io
#     - docker-buildx-plugin
#     - docker-compose-plugin


- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Uninstall conflicting packages
  apt:
    name: "{{ item }}"
    state: absent
    update_cache: yes
  loop:
    - docker.io
    - docker-doc
    - docker-compose
    - docker-compose-v2
    - podman-docker
    - containerd
    - containerd.io
    - runc

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - docker.io
    - docker-ce
    - docker-ce-cli
    - podman-docker
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin